### PR TITLE
Mergify strict mode deprecation

### LINKED ISSUE #797: Mergify strict mode deprecation
We need to fix Mergify's configuration due to https://blog.mergify.com/strict-mode-deprecation/

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #797

### CODE REVIEW

**Comment by tomwhite** [comment]
Hmm not sure how to fix the mergify config here.

**Comment by jeromekelleher** [comment]
I think we have a chicken and egg situation with #796 - how about we merge that first manually then rebase this?

**Comment by tomwhite** [comment]
Rebasing. Still not sure I have the config right though, as the `condition` in `queue_rules` duplicates that in `pull_request_rules`. It might be OK, but seems a bit redundant.

**Comment by jeromekelleher** [comment]
I doesn't seem to be rerunning, and the config looks OK to me. Maybe we should merge this manually, and see if mergify is then happy with some subsequent PRs?

**Pull request merged**
