### PR TITLE
Use the same distributed as dask

### PR DESCRIPTION
**Pull request by ravwojdyla**
Re: #374 
There seem to be some dependencies between those two (like `dask.utils`), so if we pin `dask` (like in #426), we should also pin `distributed`, otherwise users (or in this case validation suite) will experience hard to debug failures. In case of the validation suite it was a cryptic:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'stringify' from 'dask.utils' (/Users/rav/miniconda3/envs/_sgkit_test/lib/python3.8/site-packages/dask/utils.py)
```

### CODE REVIEW

**Review by tomwhite — APPROVED** [review]

**Comment by hammer** [comment]
Good catch! Is there any way to test requirements to ensure these kinds of inconsistencies are caught by code in the future?

**Comment by ravwojdyla** [comment]
@hammer I'm not sure if this issue failing validation suite counts as being caught by code? Here it might be worth noting that in the PC Relate validation we only install sgkit + pytest, which more closely represents a potential user (than for example the dev environment with all the extra dev dependencies). For future it might be interesting to add the Upstream CI with main branches of the core dependencies (#444) and run some validation use cases in environment closely resembling a potential user.

**Comment by hammer** [comment]
> I'm not sure if this issue failing validation suite counts as being caught by code?

Fair point. I had imagined something a bit closer to `requirements.txt`/`setup.cfg` where we might be able to make assertions over the dependency graph produced by `pip` or whichever tool is reading and resolving those files. I don't think it's possible or worth it though, just a thought I had.

**Comment by hammer** [comment]
(Also will this PR fix the validation suite? That would be lovely. The red box in our README makes me a little bit sad.)

**Comment by ravwojdyla** [comment]
@hammer yes, it should fix the validation suite. And yea, I get anxiety each time I see that red badge (which I guess means it's "working").

**Pull request merged**
