### PR TITLE
Add upstream CI

### PR DESCRIPTION
**Pull request by ravwojdyla**
Re #444

This is right now draft, wanna get some feedback on the approach before polishing.

### CODE REVIEW

**Comment by ravwojdyla** [comment]
@tomwhite I was expecting the upstream tests to pass given the comments in https://github.com/pystatgen/sgkit/pull/430 ~> https://github.com/dask/dask/pull/7004. But it seems like there are still failures: https://github.com/ravwojdyla/sgkit/runs/1777383393?check_suite_focus=true, is this expected?

**Comment by tomwhite** [comment]
Looks like we need dask-ml too, due to https://github.com/dask/dask-ml/commit/7d04c9519aed58c66c4e0577240e20a5ab1a3a96?

Approach looks good to me.

**Comment by ravwojdyla** [comment]
@tomwhite this is ready to review. As you can see the Upstream build is failing ([link](https://github.com/pystatgen/sgkit/pull/445/checks?check_run_id=1793482369), BUT not due to the outdated dask-ml, there are 2 separate issues that the upstreams "introduce", I suggest we fix/investigate those in separate PRs? Also should we add badge to readme? I presume upstream build will be red pretty frequently. wdyt?

**Review by tomwhite — APPROVED** [review]
Looks great - thanks for doing this.

+1 to fixing the issues causing problems in separate PRs. I think we should probably add a badge if only to surface the extent of the problem.

**Comment by ravwojdyla** [comment]
Added the badge, will merge when green.

**Pull request merged**
