### PR TITLE
Fix get_region_start to work with contig names that have colons and dashes.

### PR DESCRIPTION
**Pull request by d-laub**
Addresses issue #882.

### CODE REVIEW

**Comment by tomwhite** [comment]
Thanks for opening an issue and PR to fix it @d-laub!

The code looks good to me. Would you be able to add a short unit test of this function, perhaps in https://github.com/pystatgen/sgkit/blob/main/sgkit/tests/io/vcf/test_utils.py?

**Comment by d-laub** [comment]
@tomwhite thanks for the suggestion. I gave it a shot and caught a bug. One thing I'll note is that this function will still fail if a contig name ends with <digits>-<digits>. Hopefully no one has or will name a contig in such a way. Otherwise, let know if there's anything else I can do.

**Review by tomwhite — COMMENTED** [review]
Thanks for writing a test @d-laub. It looks good to me.

The build is failing, however, as we have pre-commit checks for import order etc. In this case, the `import re` line needs moving up, see https://github.com/pystatgen/sgkit/runs/7668388547?check_suite_focus=true#step:5:241.

You might want to  install pre-commit locally to catch these things before submitting them, see https://pystatgen.github.io/sgkit/latest/contributing.html#install and https://pystatgen.github.io/sgkit/latest/contributing.html#coding-standards

**Review by jeromekelleher — APPROVED** [review]

**Comment by tomwhite** [comment]
It looks like the latest failures are when running tests against real VCF files, not pre-commit failures. It will need some digging to see if that is a problem introduced with this change, or whether it has uncovered a bug.

I can take a look but it probably won't be for a few days.

**Comment by d-laub** [comment]
Yea I don't know how the ground truth was generated for the number of variants in those real VCF tests. My first thought was to compare to `bcftools stats` but like Tom I won't have time to dig into this for a few days.

**Comment by tomwhite** [comment]
+1 to using `bcftools` for the ground truth here.

**Comment by d-laub** [comment]
Turns out some regions end with ":\d+-" so I caught that case and now all the vcf tests passed locally. 🤞🏼

**Review by tomwhite — APPROVED** [review]
LGTM

**Pull request merged**
