### PR TITLE
Pin to Dask 2021.02.0 while incompatibility with later versions is investigated

### PR DESCRIPTION
**Pull request by tomwhite**

### CODE REVIEW

**Comment by tomwhite** [comment]
This will fix the main build and the documentation build (see #482).

**Review by ravwojdyla — APPROVED** [review]

**Review by jeromekelleher — COMMENTED** [review]
Are we sure we want to pin in setup.cfg? This does more than just fix the CI builds, doesn't it?

**Comment by tomwhite** [comment]
> Are we sure we want to pin in setup.cfg? This does more than just fix the CI builds, doesn't it?

You're right. I was hoping this pin would be short-lived, and certainly wouldn't get released.

I can just change the requirements file though for CI.

**Comment by jeromekelleher** [comment]
> You're right. I was hoping this pin would be short-lived, and certainly wouldn't get released.

Pins have a habit of persisting, I'd rather keep it to a minimum, but it's up to you really.

**Review by jeromekelleher — APPROVED** [review]

**Comment by jrbourbeau** [comment]
I'd be curious to know what changes in the Dask 2021.03.0 release impacted `sgkit` (apologies for any unexpected breakages)

**Comment by tomwhite** [comment]
> I'd be curious to know what changes in the Dask 2021.03.0 release impacted `sgkit` (apologies for any unexpected breakages)

It was this Dask PR: https://github.com/dask/dask/pull/6738. I see the problem described in #482 with that commit, but not with the one before it.

More concretely, the following prints `array(3)` with that Dask PR, and just `3` with previous versions.

```python
import numpy as np
import xarray as xr
import dask.array as da
xr.DataArray.__module__ = "xarray" # simulate sphinx workaround, which has the effect of Dask not recognising it as xarray
data = np.arange(4)
da.asarray(xr.DataArray(data)).max().compute()
```

**Comment by jrbourbeau** [comment]
Gotcha, thanks for the upstream PR in Dask!

**Pull request merged**
