### PR TITLE
Fix mypy errors with Xarray 0.17.0

### LINKED ISSUE #475: Fix mypy errors with Xarray 0.17.0
Xarray 0.17.0 declares types so some mypy ignore statements are no longer needed.

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #475

### CODE REVIEW

**Comment by ravwojdyla** [comment]
@tomwhite re my comment during the meeting, I think in our case we ended up making a change in the `.pre-commit-config.yaml` to trigger cache invalidation. So in this case it would be adding sth like `xarray>=0.17.0`?

**Comment by ravwojdyla** [comment]
@tomwhite this is the pre-commit cache key: https://github.com/pre-commit/action/blob/bd5a59564b23176961c230d5a8facdba087e2962/index.js#L53, so change in the hash of the `.pre-commit-config.yaml` will trigger invalidation. And in our case (sgkit) I think added `xarray>=0.17.0` to mypy's `additional_dependencies` is actually relatively sane (?)

**Comment by ravwojdyla** [comment]
@tomwhite but if you don't want to add the `>=0.17.0`, as a "hack" you could also just change the order of the dependencies in the mypy `additional_dependencies`, and that would likely also invalidate the cache.

**Comment by tomwhite** [comment]
Thanks @ravwojdyla! I've tried changing `additional_dependencies` to include `xarray>=0.17.0`.

**Comment by ravwojdyla** [comment]
@tomwhite I think that helped, but coincidentally we have another case of #457 :)

**Comment by tomwhite** [comment]
Merging this, since it fixes the underlying mypy issue. I'll look at the race condition separately.

**Pull request merged**
