### PR TITLE
Output plink

### LINKED ISSUE #926: Output plink
After VCF, plink is the most important format for variation data and being able to easily export would be very useful.

Can we write to binary plink with reasonable single-threaded throughput? Like VCF, I don't think writing the file in parallel is very important.

Hopefully the [to_bed](https://fastlmm.github.io/bed-reader/#bed_reader.to_bed) function in bed_reader will do this?

See also #544 and #924

### PR DESCRIPTION
**Pull request by tomwhite**
- [x] Fixes #926 
- [x] Tests added
- [x] User visible changes (including notable bug fixes) are documented in `changelog.rst`
- [x] New functions are listed in `api.rst`

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Review by benjeffery — APPROVED** [review]
LGTM

**Comment by clwgg** [comment]
Hi all, sorry to randomly butt in here, but I just came across this and wanted to say that I think this would be a great addition!
I realize this is a draft PR, but one thing that I think would be really awesome would be to give the user an option to specify a custom coordinate to populate the `pheno` property of `to_bed` with. This would make it much easier to write out to plink and directly feed into plink-based GWAS tools. Of course there's some risk to exposing a choice like that to the user, but I think if one checked that the given coordinate is of dimension `samples` and of a numerical dtype, maybe not too much can go wrong?

**Comment by jeromekelleher** [comment]
Nice idea @clwgg! Shall we create an issue to do this as a follow-up?

**Comment by tomwhite** [comment]
I agree this would be a great feature to add. Let's do it in a follow on PR.

**Comment by clwgg** [comment]
Sounds good! I'll open an issue then!

**Pull request merged**
