### PR TITLE
Pin pandas < 1.4.0 since statsmodels doesn't support this version yet.

### LINKED ISSUE #818: Fix failing build (due to Pandas 1.4.0)

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #818

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Comment by ravwojdyla** [comment]
Does it need pin in setup.cfg?

**Comment by tomwhite** [comment]
> Does it need pin in setup.cfg?

Ah yes, it does.

The tests are failing for another reason that needs checking into.

**Comment by tomwhite** [comment]
The other failure is occurring in rechunker:

```
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/rechunker/executors/dask.py:96: in <listcomp>
    stores_delayed = [_chunked_array_copy(spec) for spec in specs]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

spec = CopySpec(read=ArrayProxy(array=dask.array<concatenate, shape=(199, 2), dtype=|S1, chunksize=(199, 1), chunktype=numpy...., 2) |S1>, chunks=(199, 1)), write=ArrayProxy(array=<zarr.core.Array '/variant_allele' (199, 2) |S1>, chunks=(199, 2)))

    def _chunked_array_copy(spec: CopySpec) -> Delayed:
        """Chunked copy between arrays."""
        if spec.intermediate.array is None:
            target_store_delayed = _direct_array_copy(
                spec.read.array, spec.write.array, spec.read.chunks,
            )
    
            # fuse
            target_dsk = dask.utils.ensure_dict(target_store_delayed.dask)
            dsk_fused, _ = fuse(target_dsk)
    
            return Delayed(target_store_delayed.key, dsk_fused)
    
        else:
            # do intermediate store
            int_store_delayed = _direct_array_copy(
                spec.read.array, spec.intermediate.array, spec.read.chunks,
            )
            target_store_delayed = _direct_array_copy(
                spec.intermediate.array, spec.write.array, spec.write.chunks,
            )
    
            # now do some hacking to chain these together into a single graph.
            # get the two graphs as dicts
            int_dsk = dask.utils.ensure_dict(int_store_delayed.dask)
            target_dsk = dask.utils.ensure_dict(target_store_delayed.dask)
    
            # find the root store key representing the read
            root_keys = []
            for key in target_dsk:
                if isinstance(key, str):
                    if key.startswith("from-zarr"):
                        root_keys.append(key)
>           assert len(root_keys) == 1
E           AssertionError

/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/rechunker/executors/dask.py:74: AssertionError
```

It looks like it was caused by the latest version of Dask, specificially [this change](https://github.com/dask/dask/pull/7417). We are on an older version of rechunker (0.3.3), since we had problems with later versions.

I've opened #820 to investigate how to fix this, but in the meantime I've added a pin to avoid this Dask version.

**Comment by jeromekelleher** [comment]
LGTM - jeez this is a messy dependency graph though.

**Pull request merged**
