### PR TITLE
Set call_genotype dtype based on max_alt_alleles #640

### LINKED ISSUE #640: Use of int8 for call_genotype results in integer overflow with complex variants
I'm working with some microhaplotype variant calls in which the number of the alleles can be >300 (likely due to poor quality calls at some loci). It would be ideal if the `call_genotype` dtype was configurable and/or automatically set based on the `max_alt_alleles` parameter. Similar discussion in #584.

### PR DESCRIPTION
**Pull request by timothymillar**
Fixes #640

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Comment by jeromekelleher** [comment]
Just a quick update here @timothymillar - @tomwhite is away for a little bit and we're just waiting on him to get back to have a quick look at his. But, if you're keen to get it in, we can merge now, no problem.

**Comment by timothymillar** [comment]
Thanks @jeromekelleher, no rush from me.

**Comment by tomwhite** [comment]
LGTM

**Review by tomwhite — APPROVED** [review]

**Pull request merged**
