### PR TITLE
Add to_haplotype_calls function

### PR DESCRIPTION
**Pull request by tomwhite**
This is needed for #231, which works on haplotypes.

I'm open to suggestions for a different name (`to_haplotype_calls`), or where it lives (`model.py` at the moment).

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I'm not sure what we mean by "haplotypes" here. If we had a variant matrix V for haploids, where the rows are the genotype calls, then I'd call the columns of this matrix the "haplotypes". That is, each sample has a haplotype, which is its array of genotypes.

If we have diploid phased data, then by extension I'd say that we'd have two haplotype arrays for each sample. If the data is *unphased* then it's not clear what we mean by haplotypes, unless we arbitrarily phase them first.

**Comment by tomwhite** [comment]
I think this PR does reflect my slightly fuzzy understanding of the term "haplotype", so thanks for your clarification @jeromekelleher, that makes a lot of sense.

I don't think we need this PR now, given the changes I've made in #378, so I'm closing it. We can always revisit if it is needed for another purpose.

**Comment by hammer** [comment]
> my slightly fuzzy understanding of the term "haplotype"

Please don't feel bad about having a fuzzy understanding of this term @tomwhite! I'm 8 years in and remain confused about the many uses of "haplotype" in genetics.

**Comment by jeromekelleher** [comment]
> Please don't feel bad about having a fuzzy understanding of this term @tomwhite! I'm 8 years in and remain confused about the many uses of "haplotype" in genetics.

Totally, I have no idea what people mean by "haplotype" half the time!

**Pull request closed without merging**
