### PR TITLE
Remove mypy check in precommit

### PR DESCRIPTION
**Pull request by tomwhite**
As discussed in #862.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
:tada:

**Review by ravwojdyla — APPROVED** [review]
> I'd be OK with that. It keeps breaking, and takes a while to fix each time. All for very little gain as far as I can tell. The simplest thing would be to remove the check from precommit.

This might be a case of an observer bias, because we have mypy in place we don't see that many typing related issues? To be fair IMO typing/mypy in python is annoying to say the least (especially in numerical libs), it was and certainly feels like an afterthought, nevertheless it's better than "nothing" and I do appreciate it more over time 🤔To play devil's advocate, I myself might be making this comment from a confirmation bias perspective (coming from mostly strongly typed background).

All-in-all I'm curious if we bring it back in the future or never look back :)

**Comment by tomwhite** [comment]
Good points @ravwojdyla - I agree. Coming from a "strongly typed background" too, I had hoped that once we had added types to our code that we wouldn't need to change them. But it seems that with the numerical libraries still changing their type annotations, and mypy becoming more strict (or changing its behaviour perhaps - I'm not sure), it means that we get regular breakages. Maybe we can revisit when things settle down, but for the moment it seems like unnecessary overhead.

**Comment by tomwhite** [comment]
I merged this to try to unblock the failures on main.

**Pull request merged**
