### PR TITLE
Revert "Windows build failing with SSL error #733"

### LINKED ISSUE #737: Remove Windows SSL certs fix
Tracker issue to remove the fix introduced in #733 when a fix is available upstream.

### PR DESCRIPTION
**Pull request by tomwhite**
Test to see if reverting fixes #737

### CODE REVIEW

**Comment by tomwhite** [comment]
That seemed to work, so we can probably revert the fix.

**Comment by hammer** [comment]
What changed upstream?

**Comment by tomwhite** [comment]
I don't know. Comparing the [old failing run](https://github.com/pystatgen/sgkit/runs/3844122469?check_suite_focus=true) with the [new passing run](https://github.com/pystatgen/sgkit/runs/4209986983?check_suite_focus=true), both are on Microsoft Windows Server 2019, version 10.0.17763, but the virtual environment image has been updated from 20211003.2 to 20211110.1. There is a list of changes in https://github.com/actions/virtual-environments/commits/win19/20211110.1/images/win/Windows2019-Readme.md, but nothing that leaps out as being a fix for this (e.g. OpenSSL hasn't changed).

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Comment by jeromekelleher** [comment]
What made you think reverting might work @tomwhite (just curious)?

**Comment by tomwhite** [comment]
It's a blocker for the release, so I wondered if anything had changed on the GH actions side.

**Pull request merged**
