### PR TITLE
Initial docs for public data sets

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR migrates in some initial docs with information on a couple of public datasets. 

I'm guessing we'll ultimately want to use something like sphinx for docs, but thought this might be useful to have as simple markdown files as an interim.

Comments welcome :smile:

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM @alimanfoo, seems sensible to have some easy to access data documented. 

What's the notebook for though?

**Comment by alimanfoo** [comment]
> What's the notebook for though?

That's the notebook that builds the zarr data from the VCFs and sample metadata file then uploads to Google cloud. Thought it would be useful to include as a record of how the dataset was made.

**Comment by hammer** [comment]
Thanks @alimanfoo! I have a large collection of public datasets documented in our RS Discourse that I've been meaning to migrate up to the SMAD Discourse.

Do we want this documentation to live in this repo, in a separate repo, or on Discourse?

Do we want to subject these docs to any kind of continuous integration checks to be sure they don't go stale?

**Comment by alimanfoo** [comment]
> Thanks @alimanfoo! I have a large collection of public datasets documented in our RS Discourse that I've been meaning to migrate up to the SMAD Discourse.

Cool.
 
> Do we want this documentation to live in this repo, in a separate repo, or on Discourse?

Seemed nice to bring this together with docs on this repo at least for the time being, but happy with any option.

> Do we want to subject these docs to any kind of continuous integration checks to be sure they don't go stale?

Ultimately one option we might want to explore would be to create an [intake data catalog](https://intake.readthedocs.io/) with all the public datasets available in sgkit-readable formats. That catalog could be subject to CI checks to make sure not stale. 

Pangeo do something like that over in their [pangeo-datastore repo](https://github.com/pangeo-data/pangeo-datastore/tree/master/intake-catalogs).

Also related, I recently made an [intake catalog for MalariaGEN mosquito data](https://github.com/malariagen/intake).

**Comment by hammer** [comment]
I filed https://github.com/pystatgen/sgkit/issues/233 so that this PR would have an associated issue. @alimanfoo do you want to update this PR to add these datasets some place in our Sphinx docs, or would you rather just close this out and let someone else pick up #233?

**Pull request closed without merging**
