### PR TITLE
Support Number=G VCF fields

### LINKED ISSUE #493: Support Number=G VCF fields
See https://github.com/pystatgen/sgkit/issues/464#issuecomment-790139564 and https://github.com/pystatgen/sgkit/pull/471#issuecomment-789152592 for implementation notes.

Note that `math.comb` is only available from Python 3.8 onwards, so we may need to use `scipy.special.comb`.

cc @timothymillar

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #493

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM, although I guess we should test it one something with ploidy != 2? 

Something like
```python
import sys
import msprime

ts = msprime.sim_ancestry(3, sequence_length=10, ploidy=3, random_seed=123)
ts = msprime.sim_mutations(ts, rate=1, random_seed=456)
ts.write_vcf(sys.stdout)
```

```
##fileformat=VCFv4.2
##source=tskit 0.3.6
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=10>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  tsk_0   tsk_1   tsk_2
1       0       .       T       G,C,A   .       PASS    .       GT      3|3|3   1|3|3   3|1|1
1       1       .       A       G,C,T   .       PASS    .       GT      0|1|0   0|0|2   3|3|0
1       2       .       T       G,C,A   .       PASS    .       GT      3|1|1   1|1|2   1|0|1
1       3       .       G       C,T,A   .       PASS    .       GT      3|2|0   2|2|1   0|1|2
1       4       .       C       G,T,A   .       PASS    .       GT      1|1|0   1|1|2   0|3|1
1       5       .       G       T,A,C   .       PASS    .       GT      2|1|0   2|1|1   0|1|2
1       6       .       T       C,G,A   .       PASS    .       GT      2|0|0   2|1|0   0|2|0
1       7       .       A       G,T,C   .       PASS    .       GT      2|1|3   1|3|0   3|3|3
1       8       .       A       C,T,G   .       PASS    .       GT      1|2|2   2|2|1   2|3|2
1       9       .       C       T,G,A   .       PASS    .       GT      2|0|3   0|0|1   3|2|0
```

Although, I guess you'd have to modify the output to add in a number=G field, which would be tedious...

**Comment by tomwhite** [comment]
Thanks @jeromekelleher, nice idea. I'm not sure about adding number=G fields by hand though - seems error prone!

**Comment by jeromekelleher** [comment]
Yes, that's fair. It'd be nice to see the non diploid case tested out, but making these vcfs is a significant problem. Probably not worth it.

**Comment by timothymillar** [comment]
Thanks for doing this @tomwhite.
I'm currently working on a (mini-) haplotype assembler for short-read data as part of my thesis work which can output the GL and GP VCF fields for polyploids. I should be able to put together an example VCF for testing.

**Comment by timothymillar** [comment]
This [gist](https://gist.github.com/timothymillar/121ddb643e134d06e36a113126e988a0) has a pair of small example VCFs with tetraploid genotypes. One has the GL field and the other the GP field (both length G). These are generated from mock data as part of test suite for an unpublished tool. Hopefully they are useful until I can put some real data together.

I've tried both files with this branch without any issues. 

```python
vcf_to_zarr(
    input="simple.output.mixed_depth.likelihoods.vcf",
    output="simple.output.mixed_depth.likelihoods.zarr",
    ploidy=4,
    max_alt_alleles=3,
    fields=["FORMAT/GL"],
)
```

**Review by timothymillar — APPROVED** [review]

**Comment by tomwhite** [comment]
Thank you for generating these examples @timothymillar! I'll include one of them in the unit tests for this change.

**Pull request merged**
