### PR TITLE
`window_by_interval`

### PR DESCRIPTION
**Pull request by tomwhite**
Adds a function to create windows from arbitrary intervals, which may come from interval lists or BED files, for example. It's left to the user to load from these files (though there's an example for BED in the tests), mainly to avoid having to handle genomic coordinate conventions in sgkit itself (#434).

This provides the useful minimum needed for gene-ε (#692), where some of the examples have gene lists that I would like to convert to sgkit windows.

@timothymillar you may be interested in this, since it implements a case you brought up in [#790](https://github.com/pystatgen/sgkit/issues/790#issuecomment-1006298165).

### CODE REVIEW

**Review by timothymillar — APPROVED** [review]
LGTM, I think leaving the IO to users is the best approach for simple tabular formats.

Just out of curiosity, was there a particular reason that contig names are stored in an attribute of the dataset rather than in an array (e.g., `contig_id`)?

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Review by benjeffery — APPROVED** [review]
LGTM!

**Comment by tomwhite** [comment]
> Just out of curiosity, was there a particular reason that contig names are stored in an attribute of the dataset rather than in an array (e.g., `contig_id`)?

I looked back and found that contig names were introduced in #10, and there doesn't seem to have been any particular reason that they are stored as an attribute. Sample IDs are stored as a variable, for example. I guess we could change this, but might need to think about backward compatibility.

**Comment by timothymillar** [comment]
> I guess we could change this, but might need to think about backward compatibility.

I don't think it's a big issue, just struck me as a little inconsistent.

**Pull request merged**
