### PR TITLE
Improve/fix the validation a bit

### PR DESCRIPTION
**Pull request by ravwojdyla**
* the order in the dockerfile matters a bit (otherwise `data.table` fails to properly install)
 * fail `run.sh` if any of the cmds fail along the way

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Comment by hammer** [comment]
@ravwojdyla anything blocking this PR?

**Comment by ravwojdyla** [comment]
@hammer nope.

**Comment by hammer** [comment]
@pystatgen/committers someone want to send this in?

**Comment by jeromekelleher** [comment]
@mergifyIO update

**Pull request merged**
