### PR TITLE
Topological argsort

### PR DESCRIPTION
**Pull request by timothymillar**
Work in progress, see discussion in #844

### CODE REVIEW

**Review by jeromekelleher — COMMENTED** [review]
Looks great. Awesome to see such good perf out of the numba code here.

**Comment by timothymillar** [comment]
I think this is ready now @jeromekelleher. Although it's largely based off of the Tskit implementation so perhaps I should add an attribution?

**Comment by tomwhite** [comment]
Very nice! Do we want to add this to the published docs yet, or leave it semi private for the moment? (Happy to merge this now in either case.)

**Comment by jeromekelleher** [comment]
It would be nice to add a comment just noting that the implementation is based on tskit's, just in case someone is trying to figure it out later. 

I'm happy to merge whenever here, it's your call @timothymillar

**Comment by timothymillar** [comment]
Comment added and ready to merge. Leave it semi private for now @tomwhite, it's primarily a requirement for #845 etc. Thanks for reviewing!

**Review by jeromekelleher — APPROVED** [review]

**Pull request merged**
