### PR TITLE
Add tutorial on relationship matrices

### LINKED ISSUE #956: Example notebook exercising polyploidy and pedigree work

### PR DESCRIPTION
**Pull request by timothymillar**
- [x] Fixes #956 (doesn't cover polyploidy)

It's still a bit rough, but I think the key parts are there. This covers working with pedigree data, calculating relationship matrices from pedigree and molecular data, and combining them into a hybrid relationship matrix. It also showcases the flexibility of having sgkit based on xarray.

### CODE REVIEW

**Review by tomwhite — COMMENTED** [review]
This looks like a great addition.

I read through the text and found a few minor typos:

> It is also common to use a 0 to indicate an unknown parent pedigree files.

Change to "an unknown parent in pedigree files".

> to ensure they are note mistaken

"not"

> dimensions named "samples" and "parent"

"parents"

> Using out pedigree dataset

"our"

**Comment by timothymillar** [comment]
Thanks!

**Comment by timothymillar** [comment]
I think this is getting close now, but CI is failing due to a timeout, possibly the data download? `/home/runner/work/sgkit/sgkit/docs/examples/relatedness_tutorial.ipynb: WARNING: Executing notebook failed: CellTimeoutError [mystnb.exec]`.

I'm also having some issue with building locally as the equations in markdown cells are not being formatted correctly e.g.:
Capture

**Comment by timothymillar** [comment]
@tomwhite I was pulling the data from PMC supplementary material (not ideal). I can cut the data down to a pair of files as 1.1MB and 0.3MB. Should we upload these to the same bucket as the GWAS example?

**Comment by hammer** [comment]
Maybe? Let me check!

**Comment by hammer** [comment]
I do not see that bucket on my personal or Hammer Lab account. I may have created it with my Related Sciences account but I can no longer access that. @eric-czech do you happen to see that bucket on any RS-owned accounts?

**Comment by eric-czech** [comment]
> did you create the gs://sgkit-gwas-tutorial bucket for https://github.com/pystatgen/sgkit/issues/463?

Might have been me too but either way, I'd rather use the project and bucket we have specifically for sgkit.  I added you all (@tomwhite, @jeromekelleher, @hammer, @timothymillar) as storage object admins for https://console.cloud.google.com/storage/browser/sgkit-data.  There is a `validation` directory in there used by this [workflow](https://github.com/pystatgen/sgkit/blob/a140316e0f493da25ce9891b9277ea4689321dc0/.github/workflows/validation.yml#L22) so I think a `tutorial` directory at the top level would make sense.  @hammer and @tomwhite I also added you as owners on the GCP project so I believe you should be able to add/remove people from GCS IAM roles in the future.

@timothymillar can you upload this to `gs://sgkit-data/tutorial/<whatever_you_like>`? Let me know if you get some kind of permissions error.

**Comment by timothymillar** [comment]
Thanks @eric-czech, I was able to create the `tutorial` dir through the GUI but failing to upload data with a generic "Error".

**Comment by eric-czech** [comment]
> Edit: Ahh, it's because the whole bucket is set up as "requester pays" which I think means it won't work for tutorials anyway

Ok, I disabled that.  Try again?  Everybody I mentioned above should have full control over the bucket now.

**Comment by timothymillar** [comment]
Thanks, I've uploaded the data now. The only remaining issue is that the bucket grants read access to "allAuthenticatedUsers" rather than "allUsers":

> One or more bucket-level permissions grant access to everyone on the internet (allUsers) or anyone signed into a Google account (allAuthenticatedUsers).

This means a user can't just grab the data with the URL only. I should be able to make this change but thought I should check with whoever is paying the bills! This would also apply to the validation data which is a bit more substantial. This also outdates some of the [documentation](https://github.com/pystatgen/sgkit/blob/main/validation/gwas/method/pc_relate/run.sh#L14)

**Comment by eric-czech** [comment]
> The only remaining issue is that the bucket grants read access to "allAuthenticatedUsers" rather than "allUsers"

Ah, didn't realize that.  It's "allUsers" now so there should be no more restrictions.

> This also outdates some of the [documentation](https://github.com/pystatgen/sgkit/blob/main/validation/gwas/method/pc_relate/run.sh#L14)

Good catch!  That last line could be removed and it would be better if that path to the file was `https://storage.googleapis.com/sgkit-data/validation/hapmap_JPT_CHB_r23a_filtered.zip` instead.

**Comment by timothymillar** [comment]
I think this is ready to go unless there are any suggestions? I imagine it'll get updated as relevant features are added.

**Review by tomwhite — APPROVED** [review]

**Pull request merged**
