### PR TITLE
Enforce coding standards

### PR DESCRIPTION
**Pull request by tomwhite**
This uses the tools discussed in #5, except Coveralls (it does test code coverage though).

The actual code and the test are just for illustration and would be replaced by something more realistic later, such as that being discussed in other issues and in https://discourse.smadstatgen.org/t/xarray-conventions-for-variation-data/44/4.

The settings are intentionally strict: code coverage has to be 100%, and mypy is run with the `--strict` option. The latter may have to be relaxed in the future, but let's see how far we can get with it.

Comments and suggestions welcome of course.

### CODE REVIEW

**Comment by tomwhite** [comment]
I think GitHub Actions needs to be enabled to run in this repo, but I don't have permission to do that. @hammer or @eric-czech can you enable it please? (We can always turn it off if we decide to use a different CI.)

**Comment by eric-czech** [comment]
Maybe Jeff beat me to it?  It seems to be enabled afaict (https://github.com/pystatgen/sgkit/actions/new).

**Comment by tomwhite** [comment]
Thanks @eric-czech. It actually ran in my forked repo: https://github.com/tomwhite/sgkit/runs/795587237?check_suite_focus=true.

**Comment by jeromekelleher** [comment]
Looks good @tomwhite. Might be worth taking a look at pre-commit to automate some of this stuff, as I mentioned in #5.

Strict is good!

**Comment by tomwhite** [comment]
Added pre-commit. I think this probably good enough to start with - we can adjust things as needed later on.

**Comment by jeromekelleher** [comment]
LGTM. One nice thing about using pre-commit is that you can run it as part of CI. That way, you only have one definition of what the lint requirements are, and what you check in CI is the same as what users run on their end. This is how we do it with a [github action](https://github.com/tskit-dev/tskit/blob/7a33ceb9d123c0dc9c22bb1e430d0de866ca5e8b/.github/workflows/lint.yml#L23) in tskit.

**Comment by tomwhite** [comment]
@jeromekelleher good suggestion. I've replaced the previous CI linting checks with one that uses pre-commit.

**Comment by jeromekelleher** [comment]
What's the process for merging one of these PRs? Should we formalise waiting for approval for one-or-more maintainers, or what? (Maybe this is forking another process type issue?)

Anyway, I think we can merge this, as no one has complained.

**Comment by tomwhite** [comment]
Thanks @jeromekelleher. Merging this now.

> What's the process for merging one of these PRs? Should we formalise waiting for approval for one-or-more maintainers, or what?

I think we should require a +1 or approval from at least one other committer/maintainer.

**Pull request merged**
