### PR TITLE
Rename 'call_genotype_non_allele' to 'call_genotype_fill'

### LINKED ISSUE #772: Rename `call_genotype_non_allele` to `call_genotype_fill`?
For consistency with a general way of specifying fill masks (https://github.com/pystatgen/vcf-zarr-spec/blob/main/vcf_zarr_spec.md#missing-and-fill-values) we might rename this variable. We could keep the "non-allele" terminology in the documentation in addition to describing it as a fill value.

Thoughts @timothymillar?

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #772

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM - I take it we didn't release call_genotype_non_allele then?

**Comment by tomwhite** [comment]
Thanks @jeromekelleher. We did release call_genotype_non_allele, so this is a breaking change (albeit one that is allowed since we are still in the 0.x.y series - so we would release this as 0.5.0). However, I wonder how many people are using the variable ploidy stuff apart from @timothymillar.

**Comment by jeromekelleher** [comment]
Sounds good @tomwhite - I guess we should just mark this as a breaking change in the release notes so that we don't forget about it? You never really know who's using what.

**Comment by tomwhite** [comment]
I created a "breaking change" label for the issue so we can track this.

**Pull request merged**
