### PR TITLE
Toggle numba caching by environment variable

### LINKED ISSUE #371: Create a local version of guvectorize
That has `nopython=True` and `cache=True`, so they don't get inadvertently missed on new functions. See https://github.com/pystatgen/sgkit/pull/364#discussion_r515922535

### LINKED ISSUE #869: Disable numba caching via environment variable
Edit: related to #371

I've recently started experimenting with sgkit on a [SLURM cluster](https://jobqueue.dask.org/en/latest/generated/dask_jobqueue.SLURMCluster.html) which is working well with the exception of methods using `guvectorize` with `cache=True`. Calling these functions results in a segmentation fault on the worker. This only seems to be an issue with `guvectorize` (not the `jit` or `vectorize` decorators) and there is no segmentation fault if I set `cache=False`.

There are a couple of open issues that may be related although neither quite match what I'm seeing (need to dig some more): 
- https://github.com/dask/distributed/issues/3450
- https://github.com/numba/numba/issues/4807

There is also an open issue for globally disabling numba caching which would provide a workaround although it might be stale:
- https://github.com/numba/numba/issues/4549

In the meantime, for the sake of debugging and workarounds, it'd be useful to be able to disable numba-caching in sgkit using an environment variable.

### PR DESCRIPTION
**Pull request by timothymillar**
Fixes #371 and #869 

This is just a suggestion and I'm not sure of the best way to test this in CI unless we create an additional runner?

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Totally agree we should do this, but I wonder if it'd be better if we just made our own local ``jit`` decorator? This would allow us to put in library-wide defaults for things like ``cache``, as well as give us more fine-grained control of when jitting is done.

**Comment by tomwhite** [comment]
> Totally agree we should do this, but I wonder if it'd be better if we just made our own local `jit` decorator? This would allow us to put in library-wide defaults for things like `cache`, as well as give us more fine-grained control of when jitting is done.

Agree - see #371.

**Comment by timothymillar** [comment]
Ah, thanks I hadn't noticed that issue. I can make a start on custom `jit`, `vectorise` and `guvectorise` decorators.

**Comment by tomwhite** [comment]
Nice! I'm not sure how easy it would be to completely disable numba for `vectorize` and `guvectorize` since these wrappers change the type signature in a way that is non-trivial to do in pure python. We don't need that here though (but I'll note that it would be useful for #803) - just a way to enforce numba caching consistently.

**Comment by timothymillar** [comment]
I've started with some simple wrappers for `jit` and `guvectorize`. I ran into this issue https://github.com/numba/numba/issues/8231 when wrapping `vectorize`, but then realized that the only use of it (mine) was completely unnecessary 🤷. As @tomwhite pointed out, we can't really disable numba when using `guvectorize` so I'm ignoring that for now. I'm also leaving out `cuda` for now as I don't have convenient means to test it.

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Comment by timothymillar** [comment]
@tomwhite are you happy that this satisfies #371? Or would you prefer to also handle `@cuda` now?

**Comment by tomwhite** [comment]
@timothymillar sorry I was away last week on vacation and have only just got back. I'm fine leaving cuda for now.

**Comment by timothymillar** [comment]
No worries, thanks @tomwhite

**Pull request merged**
