### PR TITLE
Workaround dask#6631

### PR DESCRIPTION
**Pull request by ravwojdyla**
Re: #245

### CODE REVIEW

**Review by eric-czech — APPROVED** [review]

**Comment by eric-czech** [comment]
heh I have to believe that's not a change they intended.

**Comment by ravwojdyla** [comment]
@eric-czech this is definitely a bug, see https://github.com/dask/dask/issues/6631 for an analysis, this essentially broke all dunder ops between Dask Array and non-scalar ...

**Comment by eric-czech** [comment]
Crazy that it didn't break a test somewhere!

**Comment by tomwhite** [comment]
We could also exclude Dask version 2.26.0, but this works too.

I'm going to merge this manually now so we can move forward.

**Pull request merged**
