### PR TITLE
Add news pages

### LINKED ISSUE #682: Add a blog
https://predictablynoisy.com/posts/2020/sphinx-blogging has useful links

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #682

Not ready for merge since we need some content in the first post.

### CODE REVIEW

**Comment by hammer** [comment]
@tomwhite what is the best way for me to draft a blog post while this PR is not yet merged?

**Comment by hammer** [comment]
@tomwhite it looks like it's easy for me to just add text to the blog post and commit directly to this PR. You can then squash the commits down before we merge. Does that make sense to you as the best way forward?

**Comment by tomwhite** [comment]
Sounds good to me.

**Comment by hammer** [comment]
@tomwhite @jeromekelleher I put a first draft of a first blog post up with a tentative date of next Monday, August 1. Let me know what y'all think!

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Comment by tomwhite** [comment]
Thanks @hammer! I'm away on vacation this week, but will take a look next week (unless it gets merged first).

**Comment by hammer** [comment]
I went ahead and merged this PR, I'm not sure what will happen next!

**Pull request merged**
