### PR TITLE
Add `display_pedigree` method

### LINKED ISSUE #1097: Pedigree visualisation
Add a simple method for pedigree visualization using graphviz.

I've been thinking about documentation/examples for working with pedigree data and one of the current limitations is visualization. I'm not intending on "publication ready" visuals, but rather a straightforward method for sense-checking data (similar to `display_genotypes`).

The simplest option is to use graphviz, which is already an optional dependency for visualizing dask graphs (it could still be optional). This won't be very performant for larger pedigrees, but it should be good enough for common use-cases. We can allow some customization by passing through arrays to use as node and edge attributes (broadcast to the appropriate size).

Here's some rough examples using the mixed-ploidy pedigree published by Hamilton and Kerr (with simulated genotypes):

Default to using sample_id as labels:
```python
visualize_pedigree(ds)
```
HK_pedigree_1 gv

Use genotype strings as labels:
```python
labels = label=genotype_as_bytes(ds.call_genotype.values[0], phased=False).astype('U')
visualize_pedigree(
    ds,
    node_attrs=dict(label=labels)
)
```
HK_pedigree_2 gv

Indicating gametic ploidy (tau) with edge style:
```python
edges = xr.where(
    ds.stat_Hamilton_Kerr_tau == 2,
    "black:black",
    "black",
)
visualize_pedigree(
    ds,
    node_attrs=dict(label=labels),
    edge_attrs=dict(color=edges),  # broadcast to (samples * parents)
)
````
HK_pedigree_3 gv

### PR DESCRIPTION
**Pull request by timothymillar**
- [x] Fixes #1097
- [x] Tests added
- [x] User visible changes (including notable bug fixes) are documented in `changelog.rst`
- [x] New functions are listed in `api.rst`

This scales well enough to a couple of thousand samples which is well beyond the limit of legibility.

### CODE REVIEW

**Comment by timothymillar** [comment]
Still need to update dependencies for CI.

**Review by jeromekelleher — APPROVED** [review]
Nice!

**Review by benjeffery — APPROVED** [review]
LGTM!

**Comment by timothymillar** [comment]
@tomwhite can you double check that I haven't missed anything with changes to dependencies? I've skipped coverage of the except block for simplicity in CI. Otherwise, this is ready to go. The failures on Windows seem to be unrelated (bgen and plink IO).

**Review by tomwhite — APPROVED** [review]
LGTM

**Comment by jeromekelleher** [comment]
Don't know why mergify doesn't like this, merging manually.

**Pull request merged**
